### PR TITLE
fix: bad call or return

### LINKED ISSUE #13: Fix bad call
### Describe your issue

I have to fix some bug that I discover duing implementation.

### Steps to reproduce

I have to fix:

- return of getManifest function in IGraphicsProvider
- interface return in shared_ptr of createInstance function in IGameProvider
- include in export.cpp.example in games
- SHARED_STRINGIFY in Libraries.hpp 

### What was the expected result?

_No response_

### Put here any screenshots or videos (optional)

_No response_

### PR DESCRIPTION
**Pull request by AxelF44**
## Changes made

I have to fix:

    return of getManifest function in IGraphicsProvider
    interface return in shared_ptr of createInstance function in IGameProvider
    include in export.cpp.example in games
    SHARED_STRINGIFY in Libraries.hpp

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: because it's just a fix of interface
- [ ] I need help with writing tests

### CODE REVIEW

**Review by Yann-Masson — DISMISSED** [review]

File: games/export.cpp.example [hunk 1]
```diff
@@ -6,15 +6,15 @@
...
+#include "../types/Libraries.hpp"
 
 extern "C" {
     shared::types::LibraryType SHARED_LIBRARY_TYPE_GETTER_NAME(void)
     {
         return shared::types::LibraryType::GAME;
     }
 
-    std::shared_ptr<shared::games::IGame> SHARED_GRAPHICS_FACTORY_LOADER_NAME(void)
+    std::shared_ptr<shared::games::IGameProvider> SHARED_GRAPHICS_FACTORY_LOADER_NAME(void)
```
Comment (flavien-chenu) [inline games/export.cpp.example]:
```suggestion
    std::shared_ptr<shared::games::IGameProvider> SHARED_GRAPHICS_PROVIDER_LOADER_NAME(void)
```

**Review by flavien-chenu — CHANGES_REQUESTED** [review]
Please rename macro

**Review by Yann-Masson — DISMISSED** [review]

**Review by flavien-chenu — DISMISSED** [review]
200 OK.

**Review by TekMath — DISMISSED** [review]

**Review by TekMath — APPROVED** [review]

**Review by Yann-Masson — APPROVED** [review]

**Review by flavien-chenu — APPROVED** [review]
200 OK.

**Review by sdragos1 — APPROVED** [review]
200 OK
